spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true