spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    # url: jdbc:mysql://localhost:3306/events
    # username: root
    # password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
